language: go
install: true
sudo: required
go:
  - 1.9
jobs:
  fast_finish: true
  include:
    - stage: test
      before_script:
        - true
      before_install:
        - go env && pwd
      script: make test
    - stage: lint
      script:
        - while true; do echo .; sleep 30; done & make lint