language: go
install: true
sudo: required
go:
  - 1.9.0
  - tip
jobs:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - stage: test
      script: make test
    - stage: lint
      script:
        - while true; do echo .; sleep 30; done & make lint