language: go
install: true
sudo: required
addons:
  apt:
    packages:
      - docker-ce
go:
  - 1.9
jobs:
  fast_finish: true
  include:
    - script: make test
    - stage: lint
      script:
        - while true; do echo .; sleep 30; done & make lint
    - stage: push to docker
      script:
        - make push