language: go
install: true
sudo: required
go:
  - 1.9
  - tip
jobs:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - stage: test
      script: make test
    - stage: lint
      before_script:
        - true
      before_install:
        - go env && pwd
      script:
        - while true; do echo .; sleep 30; done & make lint