language: go
install: true
sudo: required
go:
  - 1.9
  - tip
jobs:
  fast_finish: true
  include:
    - script: make test
    - stage: lint
      script:
        - while true; do echo .; sleep 30; done & make lint